-- colorscheme-sync/adapters/delta.lua
local common = require("colorscheme-sync.adapters.common")
local palette = require("colorscheme-sync.palette")

local M = {}

function M.palette_for(ctx)
  local profile = ctx.profile
  if type(profile.delta) == "string" and profile.delta ~= "" then
    return profile.delta
  end
  local mode = M._theme_mode(ctx)
  return mode == "light" and "catppuccin-latte" or "catppuccin-mocha"
end

function M.features_for(delta_palette)
  return table.concat({ delta_palette, "side-by-side", "line-numbers", "decorations" }, " ")
end

function M._theme_mode(ctx)
  local theme = ctx.theme
  if type(theme) == "table" and theme.opts and theme.opts.background then
    return theme.opts.background
  end
  return vim.o.background or "dark"
end

function M.write_generated_config(path, theme_key, colors, delta_features)
  common.write_lines(path, {
    "# Auto-generated by colorscheme-sync.nvim",
    "# Theme key: " .. common.sanitize_key(theme_key),
    "[delta]",
    "\tfeatures = " .. delta_features,
    "\tsyntax-theme = none",
    "\tplus-style = syntax \"" .. colors.ok_bg .. "\"",
    "\tminus-style = syntax \"" .. colors.error_bg .. "\"",
    "\tplus-emph-style = bold syntax \"" .. colors.ok_emph_bg .. "\"",
    "\tminus-emph-style = bold syntax \"" .. colors.error_emph_bg .. "\"",
    "\thunk-header-style = syntax \"" .. colors.selection .. "\"",
    "\thunk-header-decoration-style = \"" .. colors.accent .. "\" box",
    "\tfile-style = bold \"" .. colors.accent .. "\"",
    "\tfile-decoration-style = \"" .. colors.accent .. "\" ul",
    "\tline-numbers-left-style = \"" .. colors.error .. "\"",
    "\tline-numbers-right-style = \"" .. colors.ok .. "\"",
    "\tline-numbers-left-format = \"{nm:>3}│\"",
    "\tline-numbers-right-format = \"{np:>3}│\"",
    "\tline-numbers-plus-style = \"" .. colors.ok .. "\"",
    "\tline-numbers-minus-style = \"" .. colors.error .. "\"",
    "\tline-numbers-zero-style = \"" .. colors.selection .. "\"",
  })
end

function M.sync(ctx)
  local mode = M._theme_mode(ctx)
  local colors = palette.build(mode)
  local delta_palette = M.palette_for(ctx)
  local features = M.features_for(delta_palette)
  local theme_key = type(ctx.theme) == "table" and ctx.theme.key or "default"

  local output_path = ctx.config and ctx.config.delta_config_path
    or vim.fn.expand("~/.config/git/delta-generated.gitconfig")

  pcall(M.write_generated_config, output_path, theme_key, colors, features)
end

return M
