-- colorscheme-sync/adapters/eza.lua
local common = require("colorscheme-sync.adapters.common")
local palette = require("colorscheme-sync.palette")

local M = {}

function M.color_lines(colors)
  return {
    "# Auto-generated by colorscheme-sync.nvim",
    "---",
    "filekinds:",
    "  normal:",
    "    filename:",
    "      foreground: \"" .. colors.fg .. "\"",
    "  directory:",
    "    filename:",
    "      foreground: \"" .. colors.accent .. "\"",
    "      font_style: Bold",
    "  symlink:",
    "    filename:",
    "      foreground: \"" .. colors.warn .. "\"",
    "  pipe:",
    "    filename:",
    "      foreground: \"" .. colors.warn .. "\"",
    "  blockdevice:",
    "    filename:",
    "      foreground: \"" .. colors.error .. "\"",
    "  chardevice:",
    "    filename:",
    "      foreground: \"" .. colors.error .. "\"",
    "  socket:",
    "    filename:",
    "      foreground: \"" .. colors.warn .. "\"",
    "  special:",
    "    filename:",
    "      foreground: \"" .. colors.warn .. "\"",
    "",
    "perms:",
    "  user_read:",
    "    foreground: \"" .. colors.ok .. "\"",
    "    font_style: Bold",
    "  user_write:",
    "    foreground: \"" .. colors.warn .. "\"",
    "    font_style: Bold",
    "  user_execute_file:",
    "    foreground: \"" .. colors.error .. "\"",
    "    font_style: Bold",
    "  group_read:",
    "    foreground: \"" .. colors.ok .. "\"",
    "  group_write:",
    "    foreground: \"" .. colors.warn .. "\"",
    "  group_execute:",
    "    foreground: \"" .. colors.error .. "\"",
    "  other_read:",
    "    foreground: \"" .. colors.ok .. "\"",
    "  other_write:",
    "    foreground: \"" .. colors.warn .. "\"",
    "  other_execute:",
    "    foreground: \"" .. colors.error .. "\"",
    "",
    "size:",
    "  number_byte:",
    "    foreground: \"" .. colors.ok .. "\"",
    "  number_kilo:",
    "    foreground: \"" .. colors.ok .. "\"",
    "  number_mega:",
    "    foreground: \"" .. colors.warn .. "\"",
    "  number_giga:",
    "    foreground: \"" .. colors.error .. "\"",
    "  unit:",
    "    foreground: \"" .. colors.border .. "\"",
    "",
    "users:",
    "  user_you:",
    "    foreground: \"" .. colors.accent .. "\"",
    "  group_yours:",
    "    foreground: \"" .. colors.accent .. "\"",
    "",
    "git:",
    "  new:",
    "    foreground: \"" .. colors.ok .. "\"",
    "  modified:",
    "    foreground: \"" .. colors.warn .. "\"",
    "  deleted:",
    "    foreground: \"" .. colors.error .. "\"",
    "  renamed:",
    "    foreground: \"" .. colors.accent .. "\"",
    "  typechange:",
    "    foreground: \"" .. colors.warn .. "\"",
    "  ignored:",
    "    foreground: \"" .. colors.border .. "\"",
    "  conflicted:",
    "    foreground: \"" .. colors.error .. "\"",
    "    font_style: Bold",
  }
end

function M._theme_mode(ctx)
  local theme = ctx.theme
  if type(theme) == "table" and theme.opts and theme.opts.background then
    return theme.opts.background
  end
  return vim.o.background or "dark"
end

function M.sync(ctx)
  local mode = M._theme_mode(ctx)
  local colors = palette.build(mode)
  local path = ctx.config and ctx.config.eza_theme_path
    or vim.fn.expand("~/.config/eza/theme.yml")
  pcall(common.write_text_file_if_changed, path, table.concat(M.color_lines(colors), "\n") .. "\n")
end

return M
