-- colorscheme-sync/adapters/lazygit.lua
local common = require("colorscheme-sync.adapters.common")
local palette = require("colorscheme-sync.palette")

local M = {}

function M.base_dir()
  local candidates = {
    vim.fn.expand("~/.dotfiles/Configs/lazygit/Library/Application Support/lazygit"),
    vim.fn.expand("~/Library/Application Support/lazygit"),
  }
  for _, dir in ipairs(candidates) do
    if vim.fn.isdirectory(dir) == 1 then return dir end
  end
  return candidates[#candidates]
end

function M.generated_path(theme_key)
  return string.format("%s/config-generated-%s.yml", M.base_dir(), common.sanitize_key(theme_key))
end

function M._theme_mode(ctx)
  local theme = ctx.theme
  if type(theme) == "table" and theme.opts and theme.opts.background then
    return theme.opts.background
  end
  return vim.o.background or "dark"
end

function M.write_generated_config(path, colors, delta_features)
  common.write_lines(path, {
    "# Auto-generated by colorscheme-sync.nvim",
    "gui:",
    "  theme:",
    "    activeBorderColor:",
    "      - \"" .. colors.border .. "\"",
    "      - bold",
    "    inactiveBorderColor:",
    "      - \"" .. colors.accent .. "\"",
    "    optionsTextColor:",
    "      - \"" .. colors.accent .. "\"",
    "    selectedLineBgColor:",
    "      - \"" .. colors.selection .. "\"",
    "    cherryPickedCommitBgColor:",
    "      - \"" .. colors.selection .. "\"",
    "    cherryPickedCommitFgColor:",
    "      - \"" .. colors.ok .. "\"",
    "    unstagedChangesColor:",
    "      - \"" .. colors.error .. "\"",
    "    defaultFgColor:",
    "      - \"" .. colors.fg .. "\"",
    "    searchingActiveBorderColor:",
    "      - \"" .. colors.warn .. "\"",
    "  authorColors:",
    "    \"*\": \"" .. colors.accent .. "\"",
    "git:",
    "  pagers:",
    "    - pager: delta --paging=never --features=\"" .. delta_features .. "\"",
  })
end

function M.sync(ctx)
  local delta_adapter = require("colorscheme-sync.adapters.delta")
  local mode = M._theme_mode(ctx)
  local colors = palette.build(mode)
  local delta_palette = delta_adapter.palette_for(ctx)
  local delta_features = delta_adapter.features_for(delta_palette)
  local theme_key = type(ctx.theme) == "table" and ctx.theme.key or "default"

  local generated = M.generated_path(theme_key)
  local ok_write = pcall(M.write_generated_config, generated, colors, delta_features)
  if ok_write and vim.fn.filereadable(generated) == 1 then
    vim.env.LG_CONFIG_FILE = generated
    return
  end

  local base = M.base_dir()
  local target = (mode == "light") and (base .. "/config-light.yml") or (base .. "/config.yml")
  if vim.fn.filereadable(target) == 1 then
    vim.env.LG_CONFIG_FILE = target
  end
end

return M
