-- colorscheme-sync/adapters/shell.lua
local common = require("colorscheme-sync.adapters.common")

local M = {}

function M.fzf_opts_for_mode(mode)
  if mode == "light" then
    return "--layout=reverse --no-height --color=bg+:#e6e9ef,bg:#eff1f5,spinner:#515c7a,hl:#ea76cb --color=fg:#4c4f69,header:#ea76cb,info:#8839ef,pointer:#515c7a --color=marker:#1e66f5,fg+:#4c4f69,prompt:#8839ef,hl+:#ea76cb --color=selected-bg:#ccd0da --color=border:#e6e9ef,label:#4c4f69"
  end
  return "--layout=reverse --no-height --color=bg+:#313244,bg:#1e1e2e,spinner:#f5e0dc,hl:#f38ba8 --color=fg:#cdd6f4,header:#f38ba8,info:#cba6f7,pointer:#f5e0dc --color=marker:#b4befe,fg+:#cdd6f4,prompt:#cba6f7,hl+:#f38ba8 --color=selected-bg:#45475a --color=border:#313244,label:#cdd6f4"
end

function M._theme_mode(ctx)
  local theme = ctx.theme
  if type(theme) == "table" and theme.opts and theme.opts.background then
    return theme.opts.background
  end
  return vim.o.background or "dark"
end

function M.sync(ctx)
  local lazygit_adapter = require("colorscheme-sync.adapters.lazygit")
  local mode = M._theme_mode(ctx)
  local theme_key = type(ctx.theme) == "table" and ctx.theme.key or "default"

  local bat_theme = (mode == "light") and "Catppuccin Latte" or "Catppuccin Mocha"
  local zsh_theme_file = (mode == "light")
    and "$ZSH/custom/themes/catppuccin_latte-zsh-syntax-highlighting.zsh"
    or "$ZSH/custom/themes/catppuccin_mocha-zsh-syntax-highlighting.zsh"

  local lazygit_base = lazygit_adapter.base_dir()
  local lazygit_generated = lazygit_adapter.generated_path(theme_key)
  local lazygit_fallback = lazygit_base .. ((mode == "light") and "/config-light.yml" or "/config.yml")
  local lazygit_cfg = (vim.fn.filereadable(lazygit_generated) == 1) and lazygit_generated or lazygit_fallback

  local lines = {
    "# Auto-generated by colorscheme-sync.nvim",
    "export COLORSCHEME_SYNC=1",
    "export COLORSCHEME_KEY=\"" .. theme_key .. "\"",
    "export COLORSCHEME_MODE=\"" .. mode .. "\"",
    "export BAT_THEME=\"" .. bat_theme .. "\"",
    "export FZF_DEFAULT_OPTS=\"" .. M.fzf_opts_for_mode(mode) .. "\"",
    "export LG_CONFIG_FILE=\"" .. lazygit_cfg .. "\"",
    "if [[ -n \"$ZSH\" && -f \"" .. zsh_theme_file .. "\" ]]; then",
    "  source \"" .. zsh_theme_file .. "\"",
    "fi",
  }

  local output_path = ctx.config and ctx.config.shell_sync_path
    or vim.fn.expand("~/.cache/nvim/theme-sync.zsh")
  pcall(common.write_text_file_if_changed, output_path, table.concat(lines, "\n") .. "\n")
end

return M
